title: "Bugmak的个人博客"
email: your-email@example.com
description: "一个技术爱好者的炫酷夜间博客"
baseurl: "" # 如果是根目录，就留空
url: "https://yourusername.github.io" # 替换为你的网址

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "dark"  # 夜间主题

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 5

markdown: kramdown
highlighter: rouge

author:
  name: "Bugmak"
  bio: "一个技术爱好者"
  location: "Somewhere"
  email: your-email@example.com
  github: yourusername

social:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/bugmak"
  - label: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/nonono!!!"
